### ISSUE TITLE
'"prefabdesc.customData" not found' appears whenever startup

### ISSUE THREAD

**Issue by Tobyspy** [Awbugl/ProjectGenesis#10]
Whenever loading into dysonsphere program with this mod and its requirements i always get an error message of prefabdesc.customData being not found, all of the requirements and the mod are up to date

(Image)
![image](https://user-images.githubusercontent.com/94158549/203912386-d362190f-08bc-4782-8a63-01eb936f2335.png)

**Comment by Awbugl** [comment]
It looks like the preloader of commonapi is not loaded correctly. 
Trying to follow its documentation to remove and reinstall commonapi might be helpful. 
![image](https://user-images.githubusercontent.com/56431872/203917647-2fe9ac22-7fb7-4d91-a67a-94c33044c23e.png)

**Comment by Tobyspy** [comment]
Thank you!
