### ISSUE TITLE
Multiplayer issue

### ISSUE THREAD

**Issue by m0nz** [Awbugl/ProjectGenesis#12]
Hello - firstly thank you - this is one of my favorite mods and I appreciate the work you've done.

When playing with a friend a strange thing started happening around the time we got planetary, interstellar and also Mega buildings (mega assembler, mega smelt/splitter, mega chem etc) - if one of us sets the filter on the output of a building, the other won't see the filter and it will affect the whole chain down the line - so for example, I host the game, my friend places a planetary logistics, sets all the output filters, i won't see that they are set but he will - and if you keep following it, all the things that the logistics feeds appear only for one of us - but we think it's still technically working, it just appears that it's not and make troubleshooting quite difficult haha !

**Comment by Awbugl** [comment]
So glad you enjoyed the mod! The problems you mentioned have been noticed. 
I'll do what I can to fix it, but it's hard to say when it will be fixed–especially when I can't find a tester who is available to play multiplayer.
Thanks for your feedback!

**Comment by Awbugl** [comment]
So glad you enjoyed the mod! The problems you mentioned have been noticed. 
I'll do what I can to fix it, but it's hard to say when it will be fixed–especially when I can't find a tester who is available to play multiplayer.
Thanks for your feedback!

**Comment by m0nz** [comment]
I can test and so can a friend!!! Let me know if you want help! add me on discord m0nz#4685

**Comment by Awbugl** [comment]
I will add you on discord soon xD
