### ISSUE TITLE
Location of items in the item select or replicator screen changes between menus

### ISSUE THREAD

**Issue by m0nz** [Awbugl/ProjectGenesis#15]
Wanted to open a thread but I also understand there's some limitation here with DSP

If you open your replicator and find example diamond, it should be 2nd row 4th column, but if you open another menu, say in an ILS, it will be in a different location.  

Maybe you already know this ;) 

But if not awesome... maybe move a few more things to the refining or chemical tab, Oil, water or hydrogen/oxygen maybe...

**Comment by Awbugl** [comment]
I'm sorry but it's hard to adapt. We need to leave a place for foundations and ores in the ILS, and a place for efficient recipes in the replicator screen.

**Comment by Awbugl** [comment]
suits in v2.5.5 now
