### ISSUE TITLE
English name of Graphite Coil incorrectly showing as "Grapgite Coil" v2.4.3

### ISSUE THREAD

**Issue by christopherlorking** [Awbugl/ProjectGenesis#18]
![image](https://user-images.githubusercontent.com/67563366/213112242-9159208d-af1f-434c-9c93-0da27d38e34c.png)

**Comment by Awbugl** [comment]
Thank you for your feedback! We'll fix it in the next update. 
If you see any errors, typos or not idiomatic translations, please let us know!
