### ISSUE TITLE
Memo Icons - Out of size selection window.

### ISSUE THREAD

**Issue by GabrielBallardin** [Awbugl/ProjectGenesis#20]
When selecting mat icons the selection panel is out of the correct size to cover all sections. Not allowing to select icons from the "Informatization" session for example.

![image](https://user-images.githubusercontent.com/58851234/217661709-a89a1f04-da0f-47e2-bf7e-a9fd459d63c0.png)

**Comment by Awbugl** [comment]
I need to know your game version, system version, playing platform (steam/XGP) and list of installed mods to locate this issue.
With 0.9.27.15466, Win10, steam, and only GenesisBook and its dependencies installed, we are unable to reproduce this.

**Comment by Awbugl** [comment]
![image](https://user-images.githubusercontent.com/56431872/217739310-890ba93f-c131-499d-a983-235eac8dbfa1.png)

**Comment by GabrielBallardin** [comment]
> ![image](https://user-images.githubusercontent.com/56431872/217739310-890ba93f-c131-499d-a983-235eac8dbfa1.png)

Obrigado pela correção, agora é possível selecionar ícones para as esteiras em todas as sessões. 

![image](https://user-images.githubusercontent.com/58851234/217825209-dbee8497-b05d-4544-99ab-5fa83bb3f82a.png)
