### ISSUE TITLE
Unable to craft stone dust inside materal processor.

### ISSUE THREAD

**Issue by Jaraz0** [Awbugl/ProjectGenesis#21]
Using 2.5.8 of GenesisBook, trying to craft stone dust, the mineral processor wont accept any stone and when manually placed into the machine, it freezes at 100% at never crafting the item.

![image](https://user-images.githubusercontent.com/1365605/217779513-c1d883b0-295f-472c-9f36-c9960f510633.png)

**Comment by Awbugl** [comment]
I'm sorry but it works fine in my test
what mods do you have installed? this may be caused by a mod conflict
and you can also try to rebuild them to see if the problem is solved.

**Comment by Jaraz0** [comment]
Found the issue, it was ReBuffer. Disabling the mod lets it craft.
