### ISSUE TITLE
Missing dependency error.

### ISSUE THREAD

**Issue by GabrielBallardin** [Awbugl/ProjectGenesis#24]
![image](https://user-images.githubusercontent.com/58851234/221363070-c3748119-8a22-4c53-8904-7ff6e80413c7.png)
we received an error after the last update requesting a dependency mod, but when searching for the mod it is a cheat. for infinite resources, this seems wrong to me.

![image](https://user-images.githubusercontent.com/58851234/221363163-9413e0c8-0024-4c5e-8694-0226b25de8e0.png)

**Comment by Awbugl** [comment]
This is not a mod dependency, it’s a dependency for compatibility patch.

**Comment by Awbugl** [comment]
There are only five dependencies, and we have declared them in the thunderstore.
![image](https://user-images.githubusercontent.com/56431872/221410986-d47d8241-d201-4914-9acf-81fe6c952c0d.png)

**Comment by Awbugl** [comment]
Not installing `PlanetwideMining` or other mod that we have made a compatible patch for will not cause any problems.
