### ISSUE TITLE
矿物处理厂不工作

### ISSUE THREAD

**Issue by xiyuecangxin** [Awbugl/ProjectGenesis#29]
![image](https://github.com/Awbugl/ProjectGenesis/assets/58159320/76b3b501-d5ef-4910-a286-5b6395570895)

如图

**Comment by Awbugl** [comment]
是否使用了修改制造台堆叠的mod？这类mod有可能没有考虑兼容性，把所有其他类型的工厂的堆叠设置为0.

**Comment by xiyuecangxin** [comment]
有个rebuffer，我关掉尝试下

**Comment by xiyuecangxin** [comment]
还真是
