### ISSUE TITLE
titanium coil

### ISSUE THREAD

**Issue by Frozengods** [Awbugl/ProjectGenesis#3]
This is more of the question then anything. i got to the point where i need to get titanium coils but i havent unlock it yet. i looked thought the technologies and i didnt see in with what i had left before i go to next purple matrix and some items need that item to be made with and i cant make them without the titanium coil not been research. # #

**Comment by Awbugl** [comment]
Sorry for such a slow reply. Normally the titanium coil should be unlocked with the graphite coil; if you don't see it, trying to upgrade the version and clearing the LDBTools config cache file under `.\BepInEx\config\LDBTool` may help.

**Comment by Frozengods** [comment]
Thx for the help. i try with my old game that i had the problem with it didnt work but i did try something different now it working. i think had another mods that was interfering with this mod that made it hide in it. i cant say what mods was doing it cuz i had like 30+ mods on it at that time.
