### ISSUE TITLE
Mod Incompatible not listed

### ISSUE THREAD

**Issue by Tocksson** [Awbugl/ProjectGenesis#32]
you can add Lazy Miner to the list, it completly break the snapping function of the mk miner + probably some other thing that the mod do

**Comment by Tocksson** [comment]
Add Planet Miner as well

**Comment by Awbugl** [comment]
okey, I'll add them later.

**Comment by Awbugl** [comment]
uh, could you give me a link to the `Lazy Miner` mod?
