### ISSUE TITLE
Game crashes upon loading with GB mod enabled 

### ISSUE THREAD

**Issue by Cdeeks** [Awbugl/ProjectGenesis#34]
Game will crash with error box upon loading using thunderstore mod launcher issue has happened to me around 90 hr save point and 1 other  player i know off. 
![1](https://github.com/Awbugl/ProjectGenesis/assets/28351385/01f3062b-cdb7-4717-9216-2cdc7124a4d6)

**Comment by BigPull88** [comment]
Hi,
same for me. I just updated DSP to the current version, started the game unmodded to check. Then used r2modman to update Genesis Book and dependencies, started the game modded and it was working just fine in a new game. Closed the game and restarted the DSP again from r2modman and now I get the same error message.
I tried:
- disable all mods but Genesis Book.
- use new profile and reinstalled Genesis Book and dependencies.
No luck so far.

**Comment by Cdeeks** [comment]
Ok so found oiut the game had a steam update and this is whats most likely causing mod to not work just need to wait for dev to update.

**Comment by srvanmeter87** [comment]
Same issue here. Yet another patch earlier today; hopefully it didn't wreck any of yesterday's progress, assuming HiddenCirno is working on an update currently. Thanks for all this work you've done already, Cirno.

**Comment by Bumbaras5** [comment]
The situation is similar. I haven't played for a month, I have 12 mods installed.
I double-checked everything. I reinstalled the mods. I reinstalled the game. I deleted the game settings and the cache of all mods. Nothing helped.
![Безымянный](https://github.com/Awbugl/ProjectGenesis/assets/158732635/8ee8d3ee-21f5-4100-80bd-36b84fdda369)

**Comment by Awbugl** [comment]
sorry for slow reply, GenesisBook v2.9.9 released just now which roughly adapted to the new version of DSP

**Comment by BigPull88** [comment]
Thank you! For me it's working now.
To be honest, Genesis Book is my favorite DSP mod.
