### ISSUE TITLE
开启创世之书后黑雾异常

### ISSUE THREAD

**Issue by Xujiuj** [Awbugl/ProjectGenesis#36]
打开创世之书mod后黑雾静止不攻击，靠近黑雾基地，黑雾会出来但是完全静止，黑雾的塔也不攻击，排除了多个mod，目前只有开启创世之书之后出现此类异常

**Comment by Awbugl** [comment]
我这边无法复现，请补充mod列表及对应的版本；可尝试重装全部mod
