### ISSUE TITLE
大气采集器提示该星球资源不能满足能源需求

### ISSUE THREAD

**Issue by ljzyal** [Awbugl/ProjectGenesis#39]
最新版本上在沙盒模式下建大气采集器，绝大部分星球（没有在每个行星都尝试一下，但是到目前为止还没有找到任何一个可以建大气采集器的星球，也重开了好几次了，种子也换了几个，都不行）都提示该星球资源不能满足能源需求，这是否存在问题？
mod是通过r2modman安装的（禁用了其他创世之书不需要的mod之后也是一样的情况），在8.15之前就已经安装，但是没有尝试在之前版本里使用大气采集器，不清楚是否与主程序版本更新有关
![image](https://github.com/user-attachments/assets/6eb94de7-051b-4c95-ba59-dd950eae9ffc)

**Comment by Awbugl** [comment]
已在2.9.13版本修复
