### ISSUE TITLE
[REQUEST] Customization

### ISSUE THREAD

**Issue by MaybeYouShould-GetTheHeckouttaHere** [Awbugl/ProjectGenesis#4]
Allow the player to add custom items with recipes, and add, remove or modify other recipes.
Allowing the creation of a machine which is an exact copy of the vanilla just with different speed and color might be nice...
BTW, great mod.

**Comment by Awbugl** [comment]
Sorry for the slow response. As a gameplay mod, it's not in our scope to allow such a large amount of customization (of course anyone can use the code and create a mod that supports customization).
