### ISSUE TITLE
Help, please

### ISSUE THREAD

**Issue by Gerinhuuu** [Awbugl/ProjectGenesis#40]
After the last update, when selecting a research in the technology tree, everything stops in the game. I attached a screenshot of the game with the error that appears.

Please, help me identify the mod that is causing this error.

Mods I use:

-FactoryLocator
-Dustbin
-DPSCruiseAssist
-DPSAutoPilot
-DPSDistributorSign
-LaserClearing
-LSTM
-BlueprintTweaks
-PlanetFinder
-ErrorAnalyzer
-CloseError
-CompressSave
-FractionateEverything
-MoreGraphicsOptions
-SplitterOverBelt
-BuildToolOpt
-BuildBarTool
-ReorderTechQueue

![Genesis Book Error](https://github.com/user-attachments/assets/24729740-36c0-4466-9fcc-889ca8f4a346)

**Comment by Awbugl** [comment]
v3.0 doesn't compat with saves created by v2.x
