### ISSUE TITLE
抓向多层矩阵研究站的分拣器异常

### ISSUE THREAD

**Issue by RainbowXXX** [Awbugl/ProjectGenesis#47]
在分拣器向两层或更高的研究站抓取电磁矩阵的时候，从传送带抓取1个电磁矩阵有时会增加，表现为在矩阵研究站中会变为7-10个不等，有时会减少，表现为研究站中始终没有电磁矩阵
复现步骤：
开启某一个科技的研究
搭一个两层以上的研究站
使用分拣器向第一层的研究站中供应电磁矩阵
期望表现：
当分拣器向研究站抓取一个矩阵时，研究站中就会多出一个矩阵
实际表现：
当分拣器向研究站抓取一个矩阵时，研究站中会多出7-10个电磁矩阵或者研究站中没有被抓进来的电磁矩阵

游戏版本: 0.10.31.24646
mod版本: 3.0.13

**Comment by Awbugl** [comment]
在3.0.14版本中修复
