### ISSUE TITLE
存档换到另一台电脑时，所有的巨构建筑会全部不工作

### ISSUE THREAD

**Issue by sanliuli** [Awbugl/ProjectGenesis#48]
版本：3.0.14
不清楚以前的版本有没有这种情况，工厂本身没有问题，但无法进料和出料，一定要删除传送带并重新连进出料口，才能工作。
这种时候，把不工作的建筑用蓝图复制一份，也是不行的
PC1配置：2700X+64G 2400+2080TI
PC2配置：10870H+16G 2933+3060

**Comment by starfi5h** [comment]
你有把存档文件夹中的mod文件(_存档名称.moddsv_)一起复制吗?

**Comment by Awbugl** [comment]
传送带和塔厂的链接信息储存在moddsv文件中，请检查是否复制存档时漏掉了文件。

**Comment by sanliuli** [comment]
确实是因为Moddsv的问题，已解决
