### ISSUE TITLE
缺少物品，卡关了

### ISSUE THREAD

**Issue by HalfLegend** [Awbugl/ProjectGenesis#7]
![没有](https://user-images.githubusercontent.com/10685308/200097619-59e5f1cc-3d56-461d-adfe-85af737b0f25.png)
以上几个物品我的游戏里没有，导致卡关了，有些东西造不出来
一开始我以为是mod冲突了，我特意关掉了其它所有的mod，但还是没有

**Comment by ckcz123** [comment]
你被什么物品或者科技卡关了？有的物品（比如有机晶体）是只能挖掘不能制作的

**Comment by Awbugl** [comment]
试着清一下缓存  LDBTools缓存路径:bepinex/config/ldbtool

**Comment by HalfLegend** [comment]
> 试着清一下缓存 LDBTools缓存路径:bepinex/config/ldbtool

问题解决，非常感谢！！！
问题关闭
