### ISSUE TITLE
[Question] Is this compatible with Galactic Scale?

### ISSUE THREAD

**Issue by raistlain** [Awbugl/ProjectGenesis#8]
This mod looks amazing and I would definitely like to use it. Is this compatible with Galactic Scale or would it be possible to make it compatible? There are a lot of good benefits to Galactic Scale which would pair very nicely with this mod but I haven't been able to verify.

**Comment by Shliapnik** [comment]
i play with Galactic Scale

**Comment by ckcz123** [comment]
Yes, this is compatible with Galactic Scale.
